{
 "title": "Stats per validator",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Some gauges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network ideal",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($net_ih+$net_is+$net_it)/10**9",
     "type": "math"
    }
   ]
  },
  {
   "title": "Our ideal",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($heads+$sources+$targets)/10**9",
     "type": "math"
    }
   ]
  },
  {
   "title": "Net rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($ph+$ps+$pt-$ns-$nt)/($A+$B+$C)",
     "type": "math"
    }
   ]
  },
  {
   "title": "Our rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($ph+$ps+$pt-$ns-$nt)/($A+$B+$C)",
     "type": "math"
    }
   ]
  },
  {
   "title": "Net actual",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($ph+$ps+$pt-$ns-$nt)/10**9", "type": "math" }
   ]
  },
  {
   "title": "Our actual",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($ph+$ps+$pt-$ns-$nt)/10**9", "type": "math" }
   ]
  },
  {
   "title": "Attestation rewards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Attestation rewards per location",
     "type": "table",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ETH" } },
     "targets": [
      { "expression": "$ideal_gwei/10**9", "reducer": "mean", "type": "math" },
      {
       "expression": "($actual_pos_gwei-$actual_neg_gwei)/10**9",
       "type": "math"
      },
      { "expression": "$ideal/$validators", "type": "math" },
      { "expression": "$actual/$validators", "type": "math" },
      { "expression": "$actual/$ideal", "type": "math" },
      {
       "expr": "sum by(location) (our_active_validators_per_validator)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Attestation rewards per machine",
     "type": "table",
     "gridPos": { "h": 11, "w": 18, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ETH" } },
     "targets": [
      { "expression": "$ideal_gwei/10**9", "reducer": "mean", "type": "math" },
      {
       "expression": "($actual_pos_gwei-$actual_neg_gwei)/10**9",
       "type": "math"
      },
      { "expression": "$ideal/$validators", "type": "math" },
      { "expression": "$actual/$validators", "type": "math" },
      { "expression": "$actual/$ideal", "type": "math" },
      {
       "expr": "sum by(machine) (our_active_validators_per_validator)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Attestation rewards per MEVB status",
     "type": "table",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ETH" } },
     "targets": [
      { "expression": "$ideal_gwei/10**9", "reducer": "mean", "type": "math" },
      {
       "expression": "($actual_pos_gwei-$actual_neg_gwei)/10**9",
       "type": "math"
      },
      { "expression": "$ideal/$validators", "type": "math" },
      { "expression": "$actual/$validators", "type": "math" },
      { "expression": "$actual/$ideal", "type": "math" },
      {
       "expr": "sum by(mevb_status) (our_active_validators_per_validator)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Blocks building/rewards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blocks per location",
     "type": "table",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expression": "proposed_blocks_prom", "reducer": "last", "type": "reduce" },
      { "expression": "missed_blocks_prom", "reducer": "last", "type": "reduce" },
      { "expression": "$block_reward_gwei/10**9", "type": "math" },
      { "expression": "$mev_reward_gwei/10**9", "reducer": "mean", "type": "math" }
     ]
    },
    {
     "title": "Blocks per machine",
     "type": "table",
     "gridPos": { "h": 11, "w": 18, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expression": "proposed_blocks_prom", "reducer": "last", "type": "reduce" },
      { "expression": "missed_blocks_prom", "reducer": "last", "type": "reduce" },
      { "expression": "$block_reward_gwei/10**9", "type": "math" },
      { "expression": "$mev_reward_gwei/10**9", "reducer": "mean", "type": "math" }
     ]
    },
    {
     "title": "Blocks per MEV boost",
     "type": "table",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expression": "proposed_blocks_prom", "reducer": "last", "type": "reduce" },
      { "expression": "missed_blocks_prom", "reducer": "last", "type": "reduce" },
      { "expression": "$block_reward_gwei/10**9", "type": "math" },
      { "expression": "$mev_reward_gwei/10**9", "reducer": "mean", "type": "math" },
      { "expression": "no_relay_prom", "reducer": "last", "type": "reduce" }
     ]
    },
    {
     "title": "Relay rewards (some block can be proposed by both proxies)",
     "type": "table",
     "description": "It's not summing to overall MEV reward",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count by(mev_relay)(increase(our_mev_boost_reward_per_validator_count_total[$__range])>0)",
       "legendFormat": "__auto"
      },
      { "expression": "$mev_reward_gwei/10**9", "reducer": "mean", "type": "math" }
     ]
    }
   ]
  },
  {
   "title": "Attestation rewards - graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Attestation rate - total",
     "type": "timeseries",
     "description": "Attestation rate = sum(actual rewards)/sum(ideal rewards)",
     "gridPos": { "h": 12, "w": 9, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(increase(net_actual_heads_count_total[$__range])) + sum(increase(net_actual_pos_sources_count_total[$__range])) + sum(increase(net_actual_pos_targets_count_total[$__range])) - sum(increase(net_actual_neg_sources_count_total[$__range])) - sum(increase(net_actual_neg_targets_count_total[$__range]))) / (sum(increase(net_ideal_heads_count_total[$__range])) + (sum(increase(net_ideal_sources_count_total[$__range])) + sum(increase(net_ideal_targets_count_total[$__range]))))",
       "legendFormat": "Network attestation rate"
      },
      {
       "expr": "(sum by(machine)(increase(our_actual_pos_attestations_reward_per_validator_count_total[$__range]))-sum by(machine)(increase(our_actual_neg_attestations_reward_per_validator_count_total[$__range])))/sum by(machine)(increase(our_ideal_attestations_reward_per_validator_count_total[$__range]))",
       "legendFormat": "Attestation rate of {{machine}}"
      }
     ]
    },
    {
     "title": "Attestation rate - heads",
     "type": "timeseries",
     "description": "Attestation rate = sum(actual rewards)/sum(ideal rewards)",
     "gridPos": { "h": 12, "w": 9, "x": 9, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(net_actual_heads_count_total[$__range])) / sum(increase(net_ideal_heads_count_total[$__range]))",
       "legendFormat": "Network attestation rate"
      },
      {
       "expr": "(sum by(machine)(increase(our_actual_heads_per_validator_count_total[$__range])))/sum by(machine)(increase(our_ideal_heads_per_validator_count_total[$__range]))",
       "legendFormat": "Attestation rate of {{machine}}"
      }
     ]
    },
    {
     "title": "Attestation rate - sources",
     "type": "timeseries",
     "description": "Attestation rate = sum(actual rewards)/sum(ideal rewards)",
     "gridPos": { "h": 12, "w": 9, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(increase(net_actual_pos_sources_count_total[$__range]))-sum(increase(net_actual_neg_sources_count_total[$__range]))) / sum(increase(net_ideal_sources_count_total[$__range]))",
       "legendFormat": "Network attestation rate"
      },
      {
       "expr": "(sum by(machine)(increase(our_actual_pos_sources_per_validator_count_total[$__range]))-sum by(machine)(increase(our_actual_neg_sources_per_validator_count_total[$__range])))/sum by(machine)(increase(our_ideal_sources_per_validator_count_total[$__range]))",
       "legendFormat": "Attestation rate of {{machine}}"
      }
     ]
    },
    {
     "title": "Attestation rate - targets",
     "type": "timeseries",
     "description": "Attestation rate = sum(actual rewards)/sum(ideal rewards)",
     "gridPos": { "h": 12, "w": 9, "x": 9, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(increase(net_actual_pos_targets_count_total[$__range]))-sum(increase(net_actual_neg_targets_count_total[$__range]))) / sum(increase(net_ideal_targets_count_total[$__range]))",
       "legendFormat": "Network attestation rate"
      },
      {
       "expr": "(sum by(machine)(increase(our_actual_pos_targets_per_validator_count_total[$__range]))-sum by(machine)(increase(our_actual_neg_targets_per_validator_count_total[$__range])))/sum by(machine)(increase(our_ideal_targets_per_validator_count_total[$__range]))",
       "legendFormat": "Attestation rate of {{machine}}"
      }
     ]
    }
   ]
  }
 ]
}